apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-my-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: ubuntu-first
    image: ubuntu:latest
    command: ["/bin/bash"]
    ports:
    - containerPort: 8080
